In [87]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/Self/00. Courses/Machine Learning A-Z™ Hands-On Python _ R In Data Science/00. My code/12 Model Selection

/content/drive/MyDrive/Self/00. Courses/Machine Learning A-Z™ Hands-On Python _ R In Data Science/00. My code/12 Model Selection


## Importing the libraries

In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [89]:
dataset = pd.read_csv('train.csv')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [90]:
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [91]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [92]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [93]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Training models and evaluating

In [94]:
from sklearn.metrics import r2_score

### Importing data test

In [95]:
datatest = pd.read_csv('test.csv')

In [96]:
X_test = datatest.iloc[:, :-1].values
Y_test = datatest.iloc[:, -1].values

### Multiple Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

y_pred = lin_reg.predict(X_test)
r2_score(Y_test, y_pred)

0.9286960898122536

### Support Vector Regression

In [ ]:
Y_scale = Y.reshape(len(Y), 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
sc_X.fit(X)
sc_Y.fit(Y_scale)
X_scale = sc_X.transform(X)
Y_scale = sc_Y.transform(Y_scale)

In [ ]:
Y_scale = Y.ravel()

In [ ]:
from sklearn.svm import SVR
svregressor = SVR(kernel='rbf')
svregressor.fit(X_scale, Y_scale)

y_pred = svregressor.predict(sc_X.transform(X_test))
r2_score(Y, y_pred)

0.9415876057691107

### Decision Tree Regression

In [97]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X, Y)

# y_pred = tree_reg.predict(X_test)
# r2_score(Y_test, y_pred)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

### Random Forest Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=12, random_state=0)
regressor.fit(X, Y)

y_pred = regressor.predict(X_test)
r2_score(Y_test, y_pred)

0.9932938528125368